#!/bin/sh

basedir="$(dirname "$0")"
cd "$basedir"

./espa -v A1_Alchemy_DaeCursed || exit 1
touch -t 201408021853 A1_Alchemy_DaeCursed.esp
./espa -v A1_Alchemy_Potions || exit 1
touch -t 201408031853 A1_Alchemy_Potions.esp
d/build || exit 1
rm -rf tes3cs
mkdir tes3cs
touch -t 201408101853 A.sctx.esp
touch -t 209007300000 B.sctx.esp
cp -a A1_Alchemy_DaeCursed.esp tes3cs
cp -a A1_Alchemy_Potions.esp tes3cs
mv A.sctx.esp tes3cs
mv A.sctx.au3 tes3cs
mv B.sctx.esp tes3cs
mv B.sctx.au3 tes3cs
