#!/bin/sh

basedir="$(dirname "$0")"
cd "$basedir"

./espa -v A1_Alchemy_DaeCursed || exit 1
./espa -v A1_Alchemy_Potions || exit 1
d/build || exit 1
rm -rf tes3cs
mkdir tes3cs
cp A1_Alchemy_DaeCursed.esp tes3cs
cp A1_Alchemy_Potions.esp tes3cs
mv A.sctx.esp tes3cs
mv A.sctx.au3 tes3cs
