#!/bin/sh

cd esp-assembler
stack build
root_path="$(stack path --local-install-root)"
cd ..
cp "$root_path/bin/espa" .
./espa -v A1_Alchemy_Potions
./espa -v A1_Alchemy_V4_Containers
./espa -v A1_Alchemy_V4_Apparatus
