#!/bin/sh

VERSION=1.0

basedir="$(dirname "$0")"
cd "$basedir"
cp tes3cs/A.esp A1_Alchemy_V6_Apparatus.esp || exit 1
./espa -vad -e CELL -- A1_Alchemy_V6_Apparatus.esp || exit 1
cp tes3cs/B.esp A1_Alchemy_V6_Apparatus_EVA.esp || exit 1
./espa -vad -e CELL -- A1_Alchemy_V6_Apparatus_EVA.esp || exit 1

./espa -v A1_Alchemy_V6_Containers || exit 1
touch -t 201408151853 A1_Alchemy_V6_Containers.esp
./espa -v A1_Alchemy_DaeCursed || exit 1
touch -t 201408021853 A1_Alchemy_DaeCursed.esp
./espa -v A1_Alchemy_V6_Apparatus || exit 1
touch -t 201408101853 A1_Alchemy_V6_Apparatus.esp
./espa -v A1_Alchemy_V6_Apparatus_EVA || exit 1
touch -t 209709010000 A1_Alchemy_V6_Apparatus_EVA.esp
iconv -f UTF-8 -t CP1251 README | perl -p -e 's/\n/\r\n/' > Readme.txt
iconv -f UTF-8 -t CP1251 VERSIONS | perl -p -e 's/\n/\r\n/' > Versions.txt
rm -rf A1_Alchemy_${VERSION}
rm -f A1_Alchemy_${VERSION}.zip
mkdir -p "A1_Alchemy_${VERSION}/Data Files"
cp -a Screenshots Readme.txt Versions.txt A1_Alchemy_${VERSION}
cp -a A1_Alchemy_DaeCursed.esp A1_Alchemy_Potions.esp A1_Alchemy_V6_Containers.esp A1_Alchemy_V6_Apparatus.esp A1_Alchemy_V6_Apparatus_EVA.esp "A1_Alchemy_${VERSION}/Data Files"
zip -v -X -9 -r A1_Alchemy_${VERSION}.zip A1_Alchemy_${VERSION} || exit 1
