#!/bin/sh

VERSION=0.0.3

cd esp-assembler
stack build || exit 1
root_path="$(stack path --local-install-root)"
cd ..
cp "$root_path/bin/espa" .
./espa -v A1_Alchemy_Potions || exit 1
./espa -v A1_Alchemy_V4_Containers || exit 1
./espa -v A1_Alchemy_V4_Apparatus || exit 1
./espa -v A1_Alchemy_DaeCursed || exit 1
iconv -f UTF-8 -t CP1251 README | perl -p -e 's/\n/\r\n/' > Readme.txt
iconv -f UTF-8 -t CP1251 VERSIONS | perl -p -e 's/\n/\r\n/' > Versions.txt
rm -rf A1_Alchemy_${VERSION}
rm A1_Alchemy_${VERSION}.zip
mkdir A1_Alchemy_${VERSION}
cp -r Screenshots Readme.txt Versions.txt *.esp A1_Alchemy_${VERSION}
zip -v -X -9 -r A1_Alchemy_${VERSION}.zip A1_Alchemy_${VERSION} || exit 1
