#!/bin/sh

VERSION=0.0.3

cd esp-assembler
stack build || exit 1
root_path="$(stack path --local-install-root)"
cd ..
cp "$root_path/bin/espa" .
./espa -v A1_Alchemy_Potions || exit 1
./espa -v A1_Alchemy_V4_Containers || exit 1
./espa -v A1_Alchemy_V4_Apparatus || exit 1
./espa -v A1_Alchemy_DaeCursed || exit 1
rm -rf A1_Alchemy_${VERSION}
rm A1_Alchemy_${VERSION}.zip
mkdir A1_Alchemy_${VERSION}
cp -r Screenshots Readme.txt Versions.txt *.esp A1_Alchemy_${VERSION}
zip -v -X -9 -r A1_Alchemy_${VERSION}.zip A1_Alchemy_${VERSION} || exit 1
