#!/bin/sh

basedir="$(dirname "$0")"
text="$(cat "$basedir/sc.au_")"
cat "$basedir/h.au_" > "${1}.au3"
awk -v TEXT="$text" '{
    print "";
    print "$script = \"#" $0 "\"";
    print TEXT
}' "$2" >> "${1}.au3"
