[package]
name = "PotionsBalance"
version = "0.1.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["winuser", "libloaderapi", "errhandlingapi"] }

[build-dependencies]
windres = "0.2.1"
find-winsdk = "0.2.0"
