#!/bin/sh

cat A1_Alchemy_V4_Apparatus.nosc > A1_Alchemy_V4_Apparatus.sctx
for script in scripts/*; do
  echo '' >> A1_Alchemy_V4_Apparatus.sctx
  cat $script >> A1_Alchemy_V4_Apparatus.sctx
done

../espa -v A1_Alchemy_V4_Apparatus.sctx
