#!/bin/sh

cat A1_Alchemy_V4_Apparatus.nosc > A1_Alchemy_V4_Apparatus.sctx
cd scripts
for script in *; do
  echo '' >> ../A1_Alchemy_V4_Apparatus.sctx
  echo "SCPT" >> ../A1_Alchemy_V4_Apparatus.sctx
#  echo "SCHD ${script} 0 0 0 0 0" >> ../A1_Alchemy_V4_Apparatus.sctx
  cat $script >> ../A1_Alchemy_V4_Apparatus.sctx
done
cd ..

../espa -v A1_Alchemy_V4_Apparatus.sctx
