#!/bin/sh

basedir="$(dirname "$0")"
cd "$basedir"
find scripts -type f -exec basename {} \; | sort > all_scripts
cat scripts.list | sort > sorted_scripts
diff sorted_scripts all_scripts || exit 1
rm all_scripts sorted_scripts
cat h > A.sctx
cd scripts
for script in *; do
  echo '' >> ../A.sctx
  echo "SCPT" >> ../A.sctx
  echo "SCHD ${script} 0 0 0 0 0" >> ../A.sctx
  cat $script >> ../A.sctx
done
cd ..

../espa -v A.sctx
rm A.sctx
../compile_scripts A.sctx scripts.list
mv A.sctx.esp ..
mv A.sctx.au3 ..
