#!/bin/sh

basedir="$(dirname "$0")"
cd "$basedir"
echo "MW..."
rm -rf scripts
mkdir scripts
cd scripts
python ../make_scripts.py std || exit 1
cd ..
echo "Done MW"
echo "EVA..."
rm -rf scripts_eva
mkdir scripts_eva
cd scripts_eva
python ../make_scripts.py eva || exit 1
cd ..
echo "Done EVA"

cat h > A.sctx
cd scripts
cat ../scripts.list | while read script
do
  echo '' >> ../A.sctx
  echo "SCPT" >> ../A.sctx
  echo "SCHD ${script} 0 0 0 0 0" >> ../A.sctx
  cat $script >> ../A.sctx
done
cd ..
rm -rf scripts

cat h_eva > B.sctx
cd scripts_eva
cat ../scripts_eva.list | while read script
do
  echo '' >> ../B.sctx
  echo "SCPT" >> ../B.sctx
  echo "SCHD ${script} 0 0 0 0 0" >> ../B.sctx
  cat $script >> ../B.sctx
done
cd ..
rm -rf scripts_eva

../espa -v A.sctx || exit 1
rm A.sctx
../compile_scripts A.sctx scripts.list
rm scripts.list
mv A.sctx.esp ..
mv A.sctx.au3 ..

../espa -v B.sctx || exit 1
rm B.sctx
../compile_scripts B.sctx scripts_eva.list
rm scripts_eva.list
mv B.sctx.esp ..
mv B.sctx.au3 ..
